export const EVENT_API_END_POINT = "https://farouche25.tech/api/v1/event"
export const REGISTRATION_API_END_POINT = "https://farouche25.tech/api/v1/registration"
export const RESULTS_END_POINT = "https://farouche25.tech/api/v1/results"
// export const RESULTS_END_POINT = "http://localhost:4000/api/v1/results"
// export const EVENT_API_END_POINT = "http://localhost:4000/api/v1/event"
// export const REGISTRATION_API_END_POINT = "http://localhost:4000/api/v1/registration"